application.app.name=jscrapy

##################################### h2
spring:
  h2:
    queue:
      datasource:
        url: jdbc:h2:~/.jscrapy/h2queue/jscrapy_queue;mode=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
        username: sa
        password:
        mapperpath: classpath*:mapper/*.xml

spring:
  profiles:
    active: dev

